name: Radar Genie Civil

on:
  schedule:
    - cron: '0 8,11,14,17,20 * * *' # 5 fois par jour
  workflow_dispatch: # Pour lancer manuellement

jobs:
  job-radar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install libs
        run: pip install mistralai python-telegram-bot googlesearch-python

      - name: Run script
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python PROJET_RADAR_V1.py