name: Workflow_Radar_V1

on:
  schedule:
    # # Se lance 5 fois par jour (toutes les 4h45 environ, ou aux heures choisies)
    # Ici : 08h00, 11h00, 14h00, 17h00 et 20h00 (Heure UTC)
    - cron: '0 8,11,14,17,20 * * *'
  # Permet de lancer le radar manuellement pour tester
  workflow_dispatch:

jobs:
  job-radar:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code du depot
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install libs
        run: pip install --upgrade google-generativeai python-telegram-bot

      - name: Executer le script Radar
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python PROJET_RADAR_V1.py 