name: Radar Business BTP

on:
  schedule:
    - cron: '0 */3 * * *'  # S'exécute à 00:00, 03:00, 06:00, 09:00, etc.
  workflow_dispatch:        # Permet de le lancer à la main pour tester

jobs:
  run-radar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install libs
        run: pip install mistralai python-telegram-bot requests beautifulsoup4 lxml

      - name: Run script
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python PROJET_RADAR_V1.py